# Base image
FROM node:17 as base

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire application
COPY . .

# Build the React app
RUN npm run build

# Expose port 8080 (or any desired port)
EXPOSE 8080

# Start the React app
CMD ["npm", "run", "client"]
